server:
  port: 8090
  servlet:
    context-path: /api/v1

spring:
  application:
    name: electronics-store-admin
  datasource:
    url: jdbc:mysql://localhost:3306/electronics_store?useSSL=false&serverTimezone=UTC
    username: root
    # password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
  flyway:
    baseline-on-migrate: true
    locations: classpath:db/migration
    enabled: false
  sql:
    init:
      mode: always
      schema-locations: classpath:db/migration/*.sql
      continue-on-error: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  # Secret key used to sign JWT tokens (must be Base64 encoded)
  secret: V1R5cUI0TUE3RDdTbkhGcXFkSktHV3d0WWVKY3ZXM2U1UEQyNGxLRjN3cQ==
  # Access token expiration time in milliseconds (24 hours)
  expiration: 86400000 # 24 hours
  refresh-token:
    # Refresh token expiration time in milliseconds (7 days)
    expiration: 604800000 # 7 days
    # Configure refresh token storage strategy
    # Options:
    #   - 'database' (default): More secure, tokens stored in database and can be revoked
    #   - 'jwt': Stateless JWT tokens, not stored in database (cannot be revoked server-side)
    storage: database

logging:
  level:
    org.springframework.security: DEBUG
    com.company.project: DEBUG

file:
  upload:
    dir: ./uploads/images/
    base-url: http://localhost:8090/api/v1/images/
    allowed-types: jpg,jpeg,png
    max-size: 5MB

# Add these configurations for AWS S3
storage:
  type: local # Change to 's3' for S3 storage

aws:
  credentials:
    access-key: your-access-key
    secret-key: your-secret-key
  s3:
    region: us-east-1
    bucket-name: your-bucket-name
    endpoint-url: https://s3.amazonaws.com

# Base URL for application (used in emails)
app:
  base-url: http://localhost:8090/api/v1